### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by ibn-abdulwahab** [prodevplus/UiH#13]
To write the unit tests

**Comment by ibn-abdulwahab** [comment]
I am working on this

**Comment by ibn-abdulwahab** [comment]
Please i found some tests in the test file, can you please indicate my focus classes?

**Comment by princeteck** [comment]
@AbuMuftee you have 2 task. first go thorough all the existing test case and see if they run properly or not. second their is a commented block which was not working and is for reference, please check that as well and rewrite or fix it as need to fulfill the functionality testing. 

function have a self explanatory titles or comments and should help you out in understanding its working :)

**Comment by ibn-abdulwahab** [comment]
Okay, great

**Comment by ibn-abdulwahab** [comment]
The mediaQueryData is null, can you chack that

type 'Null' is not a subtype of type 'MediaQueryData'
test\uih_test.dart 334:7  MockMediaQueryData.copyWith
test\uih_test.dart 11:10  main.<fn>.<fn>

**Comment by princeteck** [comment]
> The mediaQueryData is null, can you chack that
> 
> type 'Null' is not a subtype of type 'MediaQueryData' test\uih_test.dart 334:7 MockMediaQueryData.copyWith test\uih_test.dart 11:10 main..

I will only be able to check this out next week. have some updates planned. so will be working on it and check it out with that. let  me get back to you on next Monday or Tuesday :)
